config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :clientes, :produtos, :sessions, :tipos, :users

  get 'welcome/index'
  post 'welcome/index'

  root 'welcome#index'
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  validates :nome, length: { minimum: 3 }, presence: true
  validates :sobrenome, length: { minimum: 3 }, presence: true
  validates :sexo, inclusion: { in: %w(M F) }
  validates :uf, format: { with: /\A[a-zA-Z]{2}\z/i }
  validates :cep, format: { with: /\A[0-9]{8}\z/i }
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :authorize
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: I18n.t('activerecord.models.cliente.created') }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: I18n.t('activerecord.models.cliente.updated') }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: I18n.t('activerecord.models.cliente.updated') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :sobrenome, :endereco, :sexo, :email, :uf, :cidade, :pais, :cep,
                                      :data_nascimento, :newsletter)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.haml
= form_for(cliente, html: { class: 'w3-container', style: 'width: 50%' }) do |f|
  .field
    = f.label :nome, class: 'w3-label w3-text-theme'
    = f.text_field :nome, class: 'w3-input w3-border w3-padding-4', autofocus: 'autofocus'
  %br
  .field
    = f.label :sobrenome, class: 'w3-label w3-text-theme'
    = f.text_field :sobrenome, class: 'w3-input w3-border w3-padding-4'
  %br
  .field
    = f.label :sexo, class: 'w3-label w3-text-theme'
    = f.select(:sexo, options_for_select(get_sex), {}, {:class => 'w3-input w3-border w3-padding-4'})
  %br
  .field
    = f.label :data_nascimento, class: 'w3-label w3-text-theme'
    = f.date_field :data_nascimento, class: 'w3-input w3-border w3-padding-4'
  %br
  .field
    = f.label :endereco, class: 'w3-label w3-text-theme'
    = f.text_field :endereco, class: 'w3-input w3-border w3-padding-4'
  %br
  .field
    = f.label :cep, class: 'w3-label w3-text-theme'
    = f.text_field :cep, class: 'w3-input w3-border w3-padding-4'
  %br
  .field
    = f.label :email, class: 'w3-label w3-text-theme'
    = f.email_field :email, class: 'w3-input w3-border w3-padding-4'
  %br
  .field
    = f.label :uf, class: 'w3-label w3-text-theme'
    = f.select(:uf, options_for_select((I18n.locale == :'pt-BR' ? br_states : us_states), cliente.uf),
                    {}, {:class => 'w3-input w3-border w3-padding-4'})
  %br
  .field
    = f.label :cidade, class: 'w3-label w3-text-theme'
    = f.text_field :cidade, class: 'w3-input w3-border w3-padding-4'
  %br
  .field
    = f.label :pais, class: 'w3-label w3-text-theme'
    = f.text_field :pais, class: 'w3-input w3-border w3-padding-4'
  %br
  .field
    = f.check_box :newsletter, class: 'w3-border w3-padding-4 w3-check'
    = f.label :newsletter, class: 'w3-label w3-text-theme'
  %br
  .actions
    = f.submit
    = t('ou')
    = link_to t('voltar'), clientes_path

app/views/clientes/edit.html.haml
%h1= t('editar', scope: [:activerecord, :attributes, :cliente])
= render 'form', cliente: @cliente

app/views/clientes/index.html.haml
- if notice.present?
  %p#notice.w3-panel.w3-green.w3-padding.w3-card-8= notice
%h1= t('other', scope: [:activerecord, :models, :cliente])
%table.w3-table-all
  %thead
    %tr
      %th= t('nome', scope: [:activerecord, :attributes, :cliente])
      %th= t('sobrenome', scope: [:activerecord, :attributes, :cliente])
      %th= t('cidade', scope: [:activerecord, :attributes, :cliente])
      %th= t('uf', scope: [:activerecord, :attributes, :cliente])
      %th= t('email', scope: [:activerecord, :attributes, :cliente])
      %th{:colspan => "3"}
  %tbody
    - @clientes.each do |cliente|
      %tr
        %td= cliente.nome
        %td= cliente.sobrenome
        %td= cliente.cidade
        %td= cliente.uf
        %td= cliente.email
        %td= link_to t('exibir'), cliente
        %td= link_to t('editar'), edit_cliente_path(cliente)
        %td= link_to t('excluir'), cliente, method: :delete, data: { confirm: t('confirmar') }
%br/
= link_to t('novo', scope: [:activerecord, :attributes, :cliente]), new_cliente_path

app/views/clientes/new.html.haml
.w3-container
  - if @cliente.errors.any?
    #error_explanation.w3-panel.w3-red.w3-card-8.w3-round
      - if @cliente.errors.count == 1
        %h4= t('errors.template.header.one', model: t('activerecord.models.cliente.one'))
      - else
        %h4= t('errors.template.header.other', model: t('activerecord.models.cliente.one'),
        count: @cliente.errors.count)
      %h5= t('errors.template.body')
      %ul
        - @cliente.errors.full_messages.each do |message|
          %li= message
  %h2= t('novo', scope: [:activerecord, :attributes, :cliente])
= render 'form', cliente: @cliente

app/views/clientes/show.html.haml
%p#notice= notice
%p
  %strong= t('nome', scope: [:activerecord, :attributes, :cliente])
  = @cliente.nome
%p
  %strong= t('sobrenome', scope: [:activerecord, :attributes, :cliente])
  = @cliente.sobrenome
%p
  %strong= t('sexo', scope: [:activerecord, :attributes, :cliente])
  = @cliente.sexo
%p
  %strong= t('data_nascimento', scope: [:activerecord, :attributes, :cliente])
  = l @cliente.data_nascimento, format: :long
%p
  %strong= t('endereco', scope: [:activerecord, :attributes, :cliente])
  = @cliente.endereco
%p
  %strong= t('cep', scope: [:activerecord, :attributes, :cliente])
  = @cliente.cep
%p
  %strong= t('email', scope: [:activerecord, :attributes, :cliente])
  = @cliente.email
%p
  %strong= t('uf', scope: [:activerecord, :attributes, :cliente])
  = @cliente.uf
%p
  %strong= t('cidade', scope: [:activerecord, :attributes, :cliente])
  = @cliente.cidade
%p
  %strong= t('pais', scope: [:activerecord, :attributes, :cliente])
  = @cliente.pais
%p
  %strong= t('newsletter', scope: [:activerecord, :attributes, :cliente])
  = @cliente.newsletter

= link_to t('editar'), edit_cliente_path(@cliente)
= t('ou')
= link_to t('voltar'), clientes_path