config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :clientes, :produtos, :sessions, :tipos, :users

  get 'welcome/index'
  post 'welcome/index'

  root 'welcome#index'
end

app/models/tipo.rb
class Tipo < ApplicationRecord
  has_many :produtos, inverse_of: :tipo
  validates_presence_of :nome

  scope :all_ordered_by_nome, -> { order(:nome) }
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :authorize
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]

  # GET /tipos
  # GET /tipos.json
  def index
    @tipos = Tipo.all
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: 'Tipo was successfully created.' }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1
  # PATCH/PUT /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to @tipo, notice: 'Tipo was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: 'Tipo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_params
      params.require(:tipo).permit(:nome, :descricao)
    end
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/tipos/_form.html.haml
= form_for(tipo, html: { class: 'w3-container', style: 'width: 50%' }) do |f|
  .field
    = f.label :nome, class: 'w3-label w3-text-theme'
    = f.text_field :nome, class: 'w3-input w3-border w3-padding-4', autofocus: 'autofocus'
  %br
  .field
    = f.label :descricao, class: 'w3-label w3-text-theme'
    = f.text_area :descricao, class: 'w3-input w3-border w3-padding-4', cols:20, rows: 10
  %br
  .actions
    = f.submit
    = t('ou')
    = link_to t('voltar'), tipos_path

app/views/tipos/edit.html.haml
%h1= t('editar', scope: [:activerecord, :attributes, :tipo])
= render 'form', tipo: @tipo

app/views/tipos/index.html.haml
- if notice.present?
  %p#notice.w3-panel.w3-green.w3-padding.w3-card-8= notice
%h1= t('other', scope: [:activerecord, :models, :tipo])
%table.w3-table-all
  %thead
    %tr
      %th= t('nome', scope: [:activerecord, :attributes, :tipo])
      %th= t('descricao', scope: [:activerecord, :attributes, :tipo])
      %th{:colspan => "3"}
  %tbody
    - @tipos.each do |t|
      %tr
        %td= t.nome
        %td= truncate(t.descricao, length: 50)
        %td= link_to t('exibir'), t
        %td= link_to t('editar'), edit_tipo_path(t)
        %td= link_to t('excluir'), t, method: :delete, data: { confirm: t('confirmar') }
%br/
= link_to t('novo', scope: [:activerecord, :attributes, :tipo]), new_tipo_path

app/views/tipos/new.html.haml
.w3-container
  - if @tipo.errors.any?
    #error_explanation.w3-panel.w3-red.w3-card-8.w3-round
      - if @tipo.errors.count == 1
        %h4= t('errors.template.header.one', model: t('activerecord.models.tipo.one'))
      - else
        %h4= t('errors.template.header.other', model: t('activerecord.models.tipo.one'),
        count: @tipo.errors.count)
      %h5= t('errors.template.body')
      %ul
        - @tipo.errors.full_messages.each do |message|
          %li= message
  %h2= t('novo', scope: [:activerecord, :attributes, :tipo])
= render 'form', tipo: @tipo

app/views/tipos/show.html.haml
%p#notice= notice
%p
  %strong= t('nome', scope: [:activerecord, :attributes, :tipo])
  = @tipo.nome
%p
  %strong= t('descricao', scope: [:activerecord, :attributes, :tipo])
  = @tipo.descricao

= link_to t('editar'), edit_tipo_path(@tipo)
= t('ou')
= link_to t('voltar'), tipos_path