config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :clientes, :produtos, :sessions, :tipos, :users

  get 'welcome/index'
  post 'welcome/index'

  root 'welcome#index'
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :tipo, inverse_of: :produtos
  accepts_nested_attributes_for :tipo

  mount_uploader :image, ImageUploader

  validates_presence_of :nome, :descricao
  validates_numericality_of :valor, :greater_than => 0
  validates_numericality_of :estoque, {:greater_than => 0, only_integer: true}
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :authorize
  before_action :set_produto, only: [:show, :edit, :update, :destroy]
  before_action :get_tipos, only: [:new, :edit, :create]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all.order(:nome)
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :descricao, :valor, :estoque, :tipo_id, :image)
    end

    def get_tipos
      @tipos = Tipo.all_ordered_by_nome
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.haml
= form_for(produto, html: { class: 'w3-container', style: 'width: 50%' }) do |f|
  .field
    = f.label :nome, class: 'w3-label w3-text-theme'
    = f.text_field :nome, class: 'w3-input w3-border w3-padding-4', autofocus: 'autofocus'
  %br
  .field
    = f.label :descricao, class: 'w3-label w3-text-theme'
    = f.text_area :descricao, {class: 'w3-input w3-border w3-padding-4', cols: 20 , rows: 10}
  %br
  .field
    = f.label :tipo, class: 'w3-label w3-text-theme'
    = f.collection_select :tipo_id, @tipos, :id, :nome, {prompt: true},
    {class: 'w3-input w3-border w3-padding-4'}
  %br
  .field
    = f.label :valor, class: 'w3-label w3-text-theme'
    = f.number_field :valor, min: 1, class: 'w3-input w3-border w3-padding-4'
  %br
  .field
    = f.label :estoque, class: 'w3-label w3-text-theme'
    = f.number_field :estoque, min: 1, class: 'w3-input w3-border w3-padding-4'
  %br
  .field
    = f.label :image, class: 'w3-label w3-text-theme'
    = f.file_field :image
  %br
  .actions
    = f.submit
    = t('ou')
    = link_to t('voltar'), produtos_path

app/views/produtos/edit.html.haml
%h1= t('editar', scope: [:activerecord, :attributes, :produto])
= render 'form', produto: @produto

app/views/produtos/index.html.haml
- if notice.present?
  %p#notice.w3-panel.w3-green.w3-padding.w3-card-8= notice
%h1= t('other', scope: [:activerecord, :models, :produto])
%table.w3-table-all
  %thead
    %tr
      %th= t('nome', scope: [:activerecord, :attributes, :produto])
      %th= t('one', scope: [:activerecord, :models, :tipo])
      %th= t('descricao', scope: [:activerecord, :attributes, :produto])
      %th= t('valor', scope: [:activerecord, :attributes, :produto])
      %th= t('estoque', scope: [:activerecord, :attributes, :produto])
      %th{:colspan => "3"}
  %tbody
    - @produtos.each do |produto|
      %tr
        %td= produto.nome
        %td= produto.tipo.nome
        %td= truncate(produto.descricao)
        %td= number_to_currency produto.valor
        %td= produto.estoque
        %td= link_to t('exibir'), produto
        %td= link_to t('editar'), edit_produto_path(produto)
        %td= link_to t('excluir'), produto, method: :delete, data: { confirm: t('confirmar') }
%br/
= link_to t('novo', scope: [:activerecord, :attributes, :produto]), new_produto_path

app/views/produtos/new.html.haml
.w3-container
  - if @produto.errors.any?
    #error_explanation.w3-panel.w3-red.w3-card-8.w3-round
      - if @produto.errors.count == 1
        %h4= t('errors.template.header.one', model: t('activerecord.models.produto.one'))
      - else
        %h4= t('errors.template.header.other', model: t('activerecord.models.produto.one'),
        count: @produto.errors.count)
      %h5= t('errors.template.body')
      %ul
        - @produto.errors.full_messages.each do |message|
          %li= message
  %h2= t('novo', scope: [:activerecord, :attributes, :produto])
= render 'form', produto: @produto

app/views/produtos/show.html.haml
%p#notice= notice
%p
  %strong= t('activerecord.attributes.produto.nome')
  = @produto.nome
%p
  %strong= t('activerecord.attributes.tipo.nome')
  = @produto.tipo.nome
%p
  %strong= t('activerecord.attributes.produto.descricao')
  = @produto.descricao
%p
  %strong= t('activerecord.attributes.produto.valor')
  = @produto.valor
%p
  %strong= t('activerecord.attributes.produto.estoque')
  = @produto.estoque
%p
  %strong= t('activerecord.attributes.produto.image')
  - if @produto.image?
    = image_tag @produto.image_url
  - else
    = t('activerecord.attributes.produto.no-image')

= link_to t('editar'), edit_produto_path(@produto)
= t('ou')
= link_to t('voltar'), produtos_path