config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :clientes, :produtos, :sessions, :tipos, :users

  get 'welcome/index'
  post 'welcome/index'

  root 'welcome#index'
end

app/views/layouts/application.html.haml
!!!
%html{ :lang => 'pt-BR' }
  %head
    %meta{ :charset => 'utf-8' }
    %title Rails5 demo app
    %meta{ :name => 'viewport', :content => 'width=device-width, initial-scale=1' }
    %meta{ :name => 'description', :content => 'A Rails 5 demo app :)' }
    %meta{ :author => 'Marcelo' }
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

  %body
    %header
      #container
        %nav
          .w3-top
            %ul{ :class => 'w3-navbar w3-border w3-theme-l1' }
              %li= link_to 'Home', root_path
              - if current_user
                %li{ :class => 'w3-right'}= link_to t('auth.logout'), logout_path
                %li{ :class => 'w3-right w3-navitem'}= current_user.email
                %li= link_to t('extenso', scope: [:activerecord, :models, :cliente]), clientes_path
                %li{ :class => 'w3-dropdown-hover'}
                  =link_to t('extenso', scope: [:activerecord, :models, :produto]), produtos_path
                  .w3-dropdown-content.w3-white.w3-card-4
                    = link_to t('extenso', scope: [:activerecord, :models, :tipo]), tipos_path
                %li{ :class => 'w3-dropdown-hover' }
                  = link_to t('activerecord.models.user.extenso'), 'javascript:;'
                  .w3-dropdown-content.w3-white.w3-card-4
                    = link_to t('activerecord.attributes.user.novo'), new_user_path
              - else
                %li{ :class => 'w3-right' }= link_to t('auth.login'), login_path, { :class => 'w3-hover-theme' }
    %div{ :class => 'w3-container w3-padding-32' }
      = yield
    %footer{ :class => 'w3-container w3-theme-l1 w3-padding-16' }
      %h6= 'Rails 5 demo app'
      = form_tag('/', method: :get) do
        = select_tag 'locale',
        options_for_select(LANGUAGES, I18n.locale.to_s),
        onchange: 'this.form.submit()'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'